### ISSUE TITLE
[BUG?] Auto redirect to subdomain :80 instead of the mail one

### ISSUE THREAD

**Issue by negue** [mko-x/docker-nginx-proxy#1]
Example:

```
docker run  -d -p 80:80 -p 443:443 \
  -v /var/run/docker.sock:/tmp/docker.sock:ro \
  --name proxy \
  -e GLOB_SPDY_ENABLED="1" \
  -e GLOB_SSL_FORCE="0" \
  -e GLOB_ALLOW_HTTP_FALLBACK="1" \
  mkodockx/docker-nginx-proxy


// main container
docker run -d \
  -e VIRTUAL_HOST=domain.com \
  -e VIRTUAL_SSL_FORCE="0" \
  --name normal-nginx \
  nginx:1.7

// sub domain container

docker run -d \
  -e VIRTUAL_HOST="_my_sub.domain.com" \
  --name sub-nginx \
  nginx:1.7

```

If I stop the main container and open domain.com in the browser,  it redirects me to the sub container ...

I don't know is this a bug?

**Comment by mko-x** [comment]
Well, using this dynamic proxy there is always a default container.

The default container can be set via:

```
GLOB_DEFAULT_HOST
```

By default the first container ran becomes the default host. 

If you run _container_1_ with a top-domain and then _container_2_ with a sub-domain, then stop _container_1_
-> _container_2_ will take over the default host role and answer requests for the top-domain.
